// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (user_id, name, color, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, color, icon, is_active, created_at, updated_at
`

type CreateExpenseCategoryParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Name   string      `db:"name" json:"name"`
	Color  pgtype.Text `db:"color" json:"color"`
	Icon   pgtype.Text `db:"icon" json:"icon"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncomeCategory = `-- name: CreateIncomeCategory :one
INSERT INTO income_categories (user_id, name, color, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, color, icon, is_active, created_at, updated_at
`

type CreateIncomeCategoryParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Name   string      `db:"name" json:"name"`
	Color  pgtype.Text `db:"color" json:"color"`
	Icon   pgtype.Text `db:"icon" json:"icon"`
}

func (q *Queries) CreateIncomeCategory(ctx context.Context, arg CreateIncomeCategoryParams) (IncomeCategory, error) {
	row := q.db.QueryRow(ctx, createIncomeCategory,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i IncomeCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
UPDATE expense_categories
SET is_active = false, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type DeleteExpenseCategoryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteExpenseCategory(ctx context.Context, arg DeleteExpenseCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseCategory, arg.ID, arg.UserID)
	return err
}

const deleteIncomeCategory = `-- name: DeleteIncomeCategory :exec
UPDATE income_categories
SET is_active = false, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type DeleteIncomeCategoryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteIncomeCategory(ctx context.Context, arg DeleteIncomeCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteIncomeCategory, arg.ID, arg.UserID)
	return err
}

const getExpenseCategory = `-- name: GetExpenseCategory :one
SELECT id, user_id, name, color, icon, is_active, created_at, updated_at FROM expense_categories
WHERE id = $1 AND user_id = $2
`

type GetExpenseCategoryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetExpenseCategory(ctx context.Context, arg GetExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategory, arg.ID, arg.UserID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncomeCategory = `-- name: GetIncomeCategory :one
SELECT id, user_id, name, color, icon, is_active, created_at, updated_at FROM income_categories
WHERE id = $1 AND user_id = $2
`

type GetIncomeCategoryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetIncomeCategory(ctx context.Context, arg GetIncomeCategoryParams) (IncomeCategory, error) {
	row := q.db.QueryRow(ctx, getIncomeCategory, arg.ID, arg.UserID)
	var i IncomeCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, user_id, name, color, icon, is_active, created_at, updated_at FROM expense_categories
WHERE user_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListExpenseCategories(ctx context.Context, userID uuid.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeCategories = `-- name: ListIncomeCategories :many
SELECT id, user_id, name, color, icon, is_active, created_at, updated_at FROM income_categories
WHERE user_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListIncomeCategories(ctx context.Context, userID uuid.UUID) ([]IncomeCategory, error) {
	rows, err := q.db.Query(ctx, listIncomeCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncomeCategory{}
	for rows.Next() {
		var i IncomeCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET name = $3, color = $4, icon = $5, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, color, icon, is_active, created_at, updated_at
`

type UpdateExpenseCategoryParams struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Name   string      `db:"name" json:"name"`
	Color  pgtype.Text `db:"color" json:"color"`
	Icon   pgtype.Text `db:"icon" json:"icon"`
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, updateExpenseCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncomeCategory = `-- name: UpdateIncomeCategory :one
UPDATE income_categories
SET name = $3, color = $4, icon = $5, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, color, icon, is_active, created_at, updated_at
`

type UpdateIncomeCategoryParams struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Name   string      `db:"name" json:"name"`
	Color  pgtype.Text `db:"color" json:"color"`
	Icon   pgtype.Text `db:"icon" json:"icon"`
}

func (q *Queries) UpdateIncomeCategory(ctx context.Context, arg UpdateIncomeCategoryParams) (IncomeCategory, error) {
	row := q.db.QueryRow(ctx, updateIncomeCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i IncomeCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
