// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagToExpense = `-- name: AddTagToExpense :exec
INSERT INTO expense_tags (expense_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToExpenseParams struct {
	ExpenseID uuid.UUID `db:"expense_id" json:"expense_id"`
	TagID     uuid.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) AddTagToExpense(ctx context.Context, arg AddTagToExpenseParams) error {
	_, err := q.db.Exec(ctx, addTagToExpense, arg.ExpenseID, arg.TagID)
	return err
}

const getTagsByExpenseID = `-- name: GetTagsByExpenseID :many
SELECT t.id, t.user_id, t.name, t.color, t.created_at FROM tags t
JOIN expense_tags et ON t.id = et.tag_id
WHERE et.expense_id = $1
ORDER BY t.name
`

func (q *Queries) GetTagsByExpenseID(ctx context.Context, expenseID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByExpenseID, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllExpenseTagsByUser = `-- name: ListAllExpenseTagsByUser :many
SELECT et.expense_id, et.tag_id FROM expense_tags et
JOIN expenses e ON et.expense_id = e.id
WHERE e.user_id = $1
`

func (q *Queries) ListAllExpenseTagsByUser(ctx context.Context, userID uuid.UUID) ([]ExpenseTag, error) {
	rows, err := q.db.Query(ctx, listAllExpenseTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseTag{}
	for rows.Next() {
		var i ExpenseTag
		if err := rows.Scan(&i.ExpenseID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromExpense = `-- name: RemoveTagFromExpense :exec
DELETE FROM expense_tags
WHERE expense_id = $1 AND tag_id = $2
`

type RemoveTagFromExpenseParams struct {
	ExpenseID uuid.UUID `db:"expense_id" json:"expense_id"`
	TagID     uuid.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) RemoveTagFromExpense(ctx context.Context, arg RemoveTagFromExpenseParams) error {
	_, err := q.db.Exec(ctx, removeTagFromExpense, arg.ExpenseID, arg.TagID)
	return err
}
