// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const checkSkippedExpense = `-- name: CheckSkippedExpense :one
SELECT EXISTS (
    SELECT 1 FROM expenses
    WHERE user_id = $1
      AND expense_date >= $2
      AND expense_date <= $3
      AND status = 'skipped'
) AS is_skipped
`

type CheckSkippedExpenseParams struct {
	UserID        uuid.UUID   `db:"user_id" json:"user_id"`
	ExpenseDate   pgtype.Date `db:"expense_date" json:"expense_date"`
	ExpenseDate_2 pgtype.Date `db:"expense_date_2" json:"expense_date_2"`
}

func (q *Queries) CheckSkippedExpense(ctx context.Context, arg CheckSkippedExpenseParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSkippedExpense, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	var is_skipped bool
	err := row.Scan(&is_skipped)
	return is_skipped, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, category_id, amount, currency, description, notes, expense_date, recurring_type, priority, status, is_debt, start_date, end_date, source_rule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, category_id, amount, currency, description, notes, expense_date, recurring_type, priority, status, is_debt, start_date, end_date, source_rule_id, created_at, updated_at
`

type CreateExpenseParams struct {
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID     `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Currency      string          `db:"currency" json:"currency"`
	Description   string          `db:"description" json:"description"`
	Notes         pgtype.Text     `db:"notes" json:"notes"`
	ExpenseDate   pgtype.Date     `db:"expense_date" json:"expense_date"`
	RecurringType string          `db:"recurring_type" json:"recurring_type"`
	Priority      string          `db:"priority" json:"priority"`
	Status        string          `db:"status" json:"status"`
	IsDebt        bool            `db:"is_debt" json:"is_debt"`
	StartDate     pgtype.Date     `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date     `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID     `db:"source_rule_id" json:"source_rule_id"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.ExpenseDate,
		arg.RecurringType,
		arg.Priority,
		arg.Status,
		arg.IsDebt,
		arg.StartDate,
		arg.EndDate,
		arg.SourceRuleID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.ExpenseDate,
		&i.RecurringType,
		&i.Priority,
		&i.Status,
		&i.IsDebt,
		&i.StartDate,
		&i.EndDate,
		&i.SourceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT e.id, e.user_id, e.category_id, e.amount, e.currency, e.description, e.notes, e.expense_date, e.recurring_type, e.priority, e.status, e.is_debt, e.start_date, e.end_date, e.source_rule_id, e.created_at, e.updated_at, ec.name AS category_name, ec.color AS category_color, ec.icon AS category_icon
FROM expenses e
LEFT JOIN expense_categories ec ON e.category_id = ec.id
WHERE e.id = $1 AND e.user_id = $2
`

type GetExpenseParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type GetExpenseRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   string             `db:"description" json:"description"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate   pgtype.Date        `db:"expense_date" json:"expense_date"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	Priority      string             `db:"priority" json:"priority"`
	Status        string             `db:"status" json:"status"`
	IsDebt        bool               `db:"is_debt" json:"is_debt"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID        `db:"source_rule_id" json:"source_rule_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName  pgtype.Text        `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text        `db:"category_color" json:"category_color"`
	CategoryIcon  pgtype.Text        `db:"category_icon" json:"category_icon"`
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (GetExpenseRow, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.UserID)
	var i GetExpenseRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.ExpenseDate,
		&i.RecurringType,
		&i.Priority,
		&i.Status,
		&i.IsDebt,
		&i.StartDate,
		&i.EndDate,
		&i.SourceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryColor,
		&i.CategoryIcon,
	)
	return i, err
}

const getExpenseStatsByCategory = `-- name: GetExpenseStatsByCategory :many
SELECT
    ec.id AS category_id,
    ec.name AS category_name,
    ec.color AS category_color,
    COUNT(e.id) AS expense_count,
    COALESCE(SUM(e.amount), 0)::numeric AS total_amount
FROM expense_categories ec
LEFT JOIN expenses e ON ec.id = e.category_id
    AND e.user_id = $1
    AND ($2::date IS NULL OR e.expense_date >= $2)
    AND ($3::date IS NULL OR e.expense_date <= $3)
    AND e.status != 'skipped'
WHERE ec.user_id = $1 AND ec.is_active = true
GROUP BY ec.id, ec.name, ec.color
ORDER BY total_amount DESC
`

type GetExpenseStatsByCategoryParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetExpenseStatsByCategoryRow struct {
	CategoryID    uuid.UUID       `db:"category_id" json:"category_id"`
	CategoryName  string          `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text     `db:"category_color" json:"category_color"`
	ExpenseCount  int64           `db:"expense_count" json:"expense_count"`
	TotalAmount   decimal.Decimal `db:"total_amount" json:"total_amount"`
}

func (q *Queries) GetExpenseStatsByCategory(ctx context.Context, arg GetExpenseStatsByCategoryParams) ([]GetExpenseStatsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getExpenseStatsByCategory, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpenseStatsByCategoryRow{}
	for rows.Next() {
		var i GetExpenseStatsByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.ExpenseCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalExpensesByDateRange = `-- name: GetTotalExpensesByDateRange :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM expenses
WHERE user_id = $1
  AND expense_date >= $2
  AND expense_date <= $3
  AND status != 'skipped'
`

type GetTotalExpensesByDateRangeParams struct {
	UserID        uuid.UUID   `db:"user_id" json:"user_id"`
	ExpenseDate   pgtype.Date `db:"expense_date" json:"expense_date"`
	ExpenseDate_2 pgtype.Date `db:"expense_date_2" json:"expense_date_2"`
}

func (q *Queries) GetTotalExpensesByDateRange(ctx context.Context, arg GetTotalExpensesByDateRangeParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getTotalExpensesByDateRange, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const listAllExpensesByUser = `-- name: ListAllExpensesByUser :many
SELECT id, user_id, category_id, amount, currency, description, notes, expense_date, recurring_type, priority, status, is_debt, start_date, end_date, source_rule_id, created_at, updated_at FROM expenses
WHERE user_id = $1
ORDER BY expense_date DESC, created_at DESC
`

func (q *Queries) ListAllExpensesByUser(ctx context.Context, userID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listAllExpensesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.ExpenseDate,
			&i.RecurringType,
			&i.Priority,
			&i.Status,
			&i.IsDebt,
			&i.StartDate,
			&i.EndDate,
			&i.SourceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.user_id, e.category_id, e.amount, e.currency, e.description, e.notes, e.expense_date, e.recurring_type, e.priority, e.status, e.is_debt, e.start_date, e.end_date, e.source_rule_id, e.created_at, e.updated_at, ec.name AS category_name, ec.color AS category_color, ec.icon AS category_icon
FROM expenses e
LEFT JOIN expense_categories ec ON e.category_id = ec.id
WHERE e.user_id = $1
  AND ($2::date IS NULL OR e.expense_date >= $2)
  AND ($3::date IS NULL OR e.expense_date <= $3)
  AND ('00000000-0000-0000-0000-000000000000' = $4::uuid OR e.category_id = $4)
  AND ('' = $5 OR e.priority = $5)
  AND ('' = $6 OR e.status = $6)
  AND ('' = $7 OR e.recurring_type = $7)
ORDER BY e.expense_date DESC, e.created_at DESC
LIMIT $9 OFFSET $8
`

type ListExpensesParams struct {
	UserID        uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate     pgtype.Date `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date `db:"end_date" json:"end_date"`
	CategoryID    uuid.UUID   `db:"category_id" json:"category_id"`
	Priority      interface{} `db:"priority" json:"priority"`
	Status        interface{} `db:"status" json:"status"`
	RecurringType interface{} `db:"recurring_type" json:"recurring_type"`
	PageOffset    int32       `db:"page_offset" json:"page_offset"`
	PageLimit     int32       `db:"page_limit" json:"page_limit"`
}

type ListExpensesRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   string             `db:"description" json:"description"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate   pgtype.Date        `db:"expense_date" json:"expense_date"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	Priority      string             `db:"priority" json:"priority"`
	Status        string             `db:"status" json:"status"`
	IsDebt        bool               `db:"is_debt" json:"is_debt"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID        `db:"source_rule_id" json:"source_rule_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName  pgtype.Text        `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text        `db:"category_color" json:"category_color"`
	CategoryIcon  pgtype.Text        `db:"category_icon" json:"category_icon"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.CategoryID,
		arg.Priority,
		arg.Status,
		arg.RecurringType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.ExpenseDate,
			&i.RecurringType,
			&i.Priority,
			&i.Status,
			&i.IsDebt,
			&i.StartDate,
			&i.EndDate,
			&i.SourceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchExpenses = `-- name: SearchExpenses :many
SELECT e.id, e.user_id, e.category_id, e.amount, e.currency, e.description, e.notes, e.expense_date, e.recurring_type, e.priority, e.status, e.is_debt, e.start_date, e.end_date, e.source_rule_id, e.created_at, e.updated_at, ec.name AS category_name, ec.color AS category_color, ec.icon AS category_icon
FROM expenses e
LEFT JOIN expense_categories ec ON e.category_id = ec.id
WHERE e.user_id = $1
  AND (e.description ILIKE '%' || $2 || '%' OR e.notes ILIKE '%' || $2 || '%')
ORDER BY e.expense_date DESC, e.created_at DESC
LIMIT $4 OFFSET $3
`

type SearchExpensesParams struct {
	UserID     uuid.UUID   `db:"user_id" json:"user_id"`
	Query      pgtype.Text `db:"query" json:"query"`
	PageOffset int32       `db:"page_offset" json:"page_offset"`
	PageLimit  int32       `db:"page_limit" json:"page_limit"`
}

type SearchExpensesRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   string             `db:"description" json:"description"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate   pgtype.Date        `db:"expense_date" json:"expense_date"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	Priority      string             `db:"priority" json:"priority"`
	Status        string             `db:"status" json:"status"`
	IsDebt        bool               `db:"is_debt" json:"is_debt"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID        `db:"source_rule_id" json:"source_rule_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName  pgtype.Text        `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text        `db:"category_color" json:"category_color"`
	CategoryIcon  pgtype.Text        `db:"category_icon" json:"category_icon"`
}

func (q *Queries) SearchExpenses(ctx context.Context, arg SearchExpensesParams) ([]SearchExpensesRow, error) {
	rows, err := q.db.Query(ctx, searchExpenses,
		arg.UserID,
		arg.Query,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchExpensesRow{}
	for rows.Next() {
		var i SearchExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.ExpenseDate,
			&i.RecurringType,
			&i.Priority,
			&i.Status,
			&i.IsDebt,
			&i.StartDate,
			&i.EndDate,
			&i.SourceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skipExpense = `-- name: SkipExpense :exec
UPDATE expenses
SET status = 'skipped', updated_at = now()
WHERE id = $1 AND user_id = $2
`

type SkipExpenseParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) SkipExpense(ctx context.Context, arg SkipExpenseParams) error {
	_, err := q.db.Exec(ctx, skipExpense, arg.ID, arg.UserID)
	return err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET category_id = $3, amount = $4, currency = $5, description = $6, notes = $7,
    expense_date = $8, recurring_type = $9, priority = $10, status = $11,
    is_debt = $12, start_date = $13, end_date = $14, source_rule_id = $15,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, amount, currency, description, notes, expense_date, recurring_type, priority, status, is_debt, start_date, end_date, source_rule_id, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID     `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Currency      string          `db:"currency" json:"currency"`
	Description   string          `db:"description" json:"description"`
	Notes         pgtype.Text     `db:"notes" json:"notes"`
	ExpenseDate   pgtype.Date     `db:"expense_date" json:"expense_date"`
	RecurringType string          `db:"recurring_type" json:"recurring_type"`
	Priority      string          `db:"priority" json:"priority"`
	Status        string          `db:"status" json:"status"`
	IsDebt        bool            `db:"is_debt" json:"is_debt"`
	StartDate     pgtype.Date     `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date     `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID     `db:"source_rule_id" json:"source_rule_id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.ExpenseDate,
		arg.RecurringType,
		arg.Priority,
		arg.Status,
		arg.IsDebt,
		arg.StartDate,
		arg.EndDate,
		arg.SourceRuleID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.ExpenseDate,
		&i.RecurringType,
		&i.Priority,
		&i.Status,
		&i.IsDebt,
		&i.StartDate,
		&i.EndDate,
		&i.SourceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
