// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: income_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagToIncome = `-- name: AddTagToIncome :exec
INSERT INTO income_tags (income_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToIncomeParams struct {
	IncomeID uuid.UUID `db:"income_id" json:"income_id"`
	TagID    uuid.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) AddTagToIncome(ctx context.Context, arg AddTagToIncomeParams) error {
	_, err := q.db.Exec(ctx, addTagToIncome, arg.IncomeID, arg.TagID)
	return err
}

const getTagsByIncomeID = `-- name: GetTagsByIncomeID :many
SELECT t.id, t.user_id, t.name, t.color, t.created_at FROM tags t
JOIN income_tags it ON t.id = it.tag_id
WHERE it.income_id = $1
ORDER BY t.name
`

func (q *Queries) GetTagsByIncomeID(ctx context.Context, incomeID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByIncomeID, incomeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllIncomeTagsByUser = `-- name: ListAllIncomeTagsByUser :many
SELECT it.income_id, it.tag_id FROM income_tags it
JOIN incomes i ON it.income_id = i.id
WHERE i.user_id = $1
`

func (q *Queries) ListAllIncomeTagsByUser(ctx context.Context, userID uuid.UUID) ([]IncomeTag, error) {
	rows, err := q.db.Query(ctx, listAllIncomeTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncomeTag{}
	for rows.Next() {
		var i IncomeTag
		if err := rows.Scan(&i.IncomeID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromIncome = `-- name: RemoveTagFromIncome :exec
DELETE FROM income_tags
WHERE income_id = $1 AND tag_id = $2
`

type RemoveTagFromIncomeParams struct {
	IncomeID uuid.UUID `db:"income_id" json:"income_id"`
	TagID    uuid.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) RemoveTagFromIncome(ctx context.Context, arg RemoveTagFromIncomeParams) error {
	_, err := q.db.Exec(ctx, removeTagFromIncome, arg.IncomeID, arg.TagID)
	return err
}
