// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incomes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const checkSkippedIncome = `-- name: CheckSkippedIncome :one
SELECT EXISTS (
    SELECT 1 FROM incomes
    WHERE user_id = $1
      AND date >= $2
      AND date <= $3
      AND status = 'skipped'
) AS is_skipped
`

type CheckSkippedIncomeParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) CheckSkippedIncome(ctx context.Context, arg CheckSkippedIncomeParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSkippedIncome, arg.UserID, arg.Date, arg.Date_2)
	var is_skipped bool
	err := row.Scan(&is_skipped)
	return is_skipped, err
}

const createIncome = `-- name: CreateIncome :one
INSERT INTO incomes (user_id, category_id, amount, currency, description, notes, date, recurring_type, priority, status, start_date, end_date, source_rule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, category_id, amount, currency, description, notes, date, recurring_type, priority, status, start_date, end_date, source_rule_id, created_at, updated_at
`

type CreateIncomeParams struct {
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID     `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Currency      string          `db:"currency" json:"currency"`
	Description   string          `db:"description" json:"description"`
	Notes         pgtype.Text     `db:"notes" json:"notes"`
	Date          pgtype.Date     `db:"date" json:"date"`
	RecurringType string          `db:"recurring_type" json:"recurring_type"`
	Priority      string          `db:"priority" json:"priority"`
	Status        string          `db:"status" json:"status"`
	StartDate     pgtype.Date     `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date     `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID     `db:"source_rule_id" json:"source_rule_id"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.Date,
		arg.RecurringType,
		arg.Priority,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.SourceRuleID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.Date,
		&i.RecurringType,
		&i.Priority,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.SourceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :exec
DELETE FROM incomes
WHERE id = $1 AND user_id = $2
`

type DeleteIncomeParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteIncome(ctx context.Context, arg DeleteIncomeParams) error {
	_, err := q.db.Exec(ctx, deleteIncome, arg.ID, arg.UserID)
	return err
}

const getIncome = `-- name: GetIncome :one
SELECT i.id, i.user_id, i.category_id, i.amount, i.currency, i.description, i.notes, i.date, i.recurring_type, i.priority, i.status, i.start_date, i.end_date, i.source_rule_id, i.created_at, i.updated_at, ic.name AS category_name, ic.color AS category_color, ic.icon AS category_icon
FROM incomes i
LEFT JOIN income_categories ic ON i.category_id = ic.id
WHERE i.id = $1 AND i.user_id = $2
`

type GetIncomeParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type GetIncomeRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   string             `db:"description" json:"description"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	Date          pgtype.Date        `db:"date" json:"date"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	Priority      string             `db:"priority" json:"priority"`
	Status        string             `db:"status" json:"status"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID        `db:"source_rule_id" json:"source_rule_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName  pgtype.Text        `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text        `db:"category_color" json:"category_color"`
	CategoryIcon  pgtype.Text        `db:"category_icon" json:"category_icon"`
}

func (q *Queries) GetIncome(ctx context.Context, arg GetIncomeParams) (GetIncomeRow, error) {
	row := q.db.QueryRow(ctx, getIncome, arg.ID, arg.UserID)
	var i GetIncomeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.Date,
		&i.RecurringType,
		&i.Priority,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.SourceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryColor,
		&i.CategoryIcon,
	)
	return i, err
}

const getIncomeOccurrences = `-- name: GetIncomeOccurrences :many
SELECT id, user_id, category_id, amount, currency, description, notes, date, recurring_type, priority, status, start_date, end_date, source_rule_id, created_at, updated_at FROM incomes
WHERE user_id = $1
  AND recurring_type != 'one-time'
  AND ($2::date IS NULL OR date >= $2)
  AND ($3::date IS NULL OR date <= $3)
ORDER BY date DESC
`

type GetIncomeOccurrencesParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

func (q *Queries) GetIncomeOccurrences(ctx context.Context, arg GetIncomeOccurrencesParams) ([]Income, error) {
	rows, err := q.db.Query(ctx, getIncomeOccurrences, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.Date,
			&i.RecurringType,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.SourceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalIncomesByDateRange = `-- name: GetTotalIncomesByDateRange :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM incomes
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
  AND status != 'skipped'
`

type GetTotalIncomesByDateRangeParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) GetTotalIncomesByDateRange(ctx context.Context, arg GetTotalIncomesByDateRangeParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getTotalIncomesByDateRange, arg.UserID, arg.Date, arg.Date_2)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const listAllIncomesByUser = `-- name: ListAllIncomesByUser :many
SELECT id, user_id, category_id, amount, currency, description, notes, date, recurring_type, priority, status, start_date, end_date, source_rule_id, created_at, updated_at FROM incomes
WHERE user_id = $1
ORDER BY date DESC, created_at DESC
`

func (q *Queries) ListAllIncomesByUser(ctx context.Context, userID uuid.UUID) ([]Income, error) {
	rows, err := q.db.Query(ctx, listAllIncomesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.Date,
			&i.RecurringType,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.SourceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomes = `-- name: ListIncomes :many
SELECT i.id, i.user_id, i.category_id, i.amount, i.currency, i.description, i.notes, i.date, i.recurring_type, i.priority, i.status, i.start_date, i.end_date, i.source_rule_id, i.created_at, i.updated_at, ic.name AS category_name, ic.color AS category_color, ic.icon AS category_icon
FROM incomes i
LEFT JOIN income_categories ic ON i.category_id = ic.id
WHERE i.user_id = $1
  AND ($2::date IS NULL OR i.date >= $2)
  AND ($3::date IS NULL OR i.date <= $3)
  AND ('00000000-0000-0000-0000-000000000000' = $4::uuid OR i.category_id = $4)
  AND ('' = $5 OR i.status = $5)
  AND ('' = $6 OR i.recurring_type = $6)
ORDER BY i.date DESC, i.created_at DESC
LIMIT $8 OFFSET $7
`

type ListIncomesParams struct {
	UserID        uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate     pgtype.Date `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date `db:"end_date" json:"end_date"`
	CategoryID    uuid.UUID   `db:"category_id" json:"category_id"`
	Status        interface{} `db:"status" json:"status"`
	RecurringType interface{} `db:"recurring_type" json:"recurring_type"`
	PageOffset    int32       `db:"page_offset" json:"page_offset"`
	PageLimit     int32       `db:"page_limit" json:"page_limit"`
}

type ListIncomesRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   string             `db:"description" json:"description"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	Date          pgtype.Date        `db:"date" json:"date"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	Priority      string             `db:"priority" json:"priority"`
	Status        string             `db:"status" json:"status"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID        `db:"source_rule_id" json:"source_rule_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName  pgtype.Text        `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text        `db:"category_color" json:"category_color"`
	CategoryIcon  pgtype.Text        `db:"category_icon" json:"category_icon"`
}

func (q *Queries) ListIncomes(ctx context.Context, arg ListIncomesParams) ([]ListIncomesRow, error) {
	rows, err := q.db.Query(ctx, listIncomes,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.CategoryID,
		arg.Status,
		arg.RecurringType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomesRow{}
	for rows.Next() {
		var i ListIncomesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.Date,
			&i.RecurringType,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.SourceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skipIncome = `-- name: SkipIncome :exec
UPDATE incomes
SET status = 'skipped', updated_at = now()
WHERE id = $1 AND user_id = $2
`

type SkipIncomeParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) SkipIncome(ctx context.Context, arg SkipIncomeParams) error {
	_, err := q.db.Exec(ctx, skipIncome, arg.ID, arg.UserID)
	return err
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE incomes
SET category_id = $3, amount = $4, currency = $5, description = $6, notes = $7,
    date = $8, recurring_type = $9, priority = $10, status = $11,
    start_date = $12, end_date = $13, source_rule_id = $14,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, amount, currency, description, notes, date, recurring_type, priority, status, start_date, end_date, source_rule_id, created_at, updated_at
`

type UpdateIncomeParams struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID     `db:"category_id" json:"category_id"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Currency      string          `db:"currency" json:"currency"`
	Description   string          `db:"description" json:"description"`
	Notes         pgtype.Text     `db:"notes" json:"notes"`
	Date          pgtype.Date     `db:"date" json:"date"`
	RecurringType string          `db:"recurring_type" json:"recurring_type"`
	Priority      string          `db:"priority" json:"priority"`
	Status        string          `db:"status" json:"status"`
	StartDate     pgtype.Date     `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date     `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID     `db:"source_rule_id" json:"source_rule_id"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.Date,
		arg.RecurringType,
		arg.Priority,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.SourceRuleID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.Date,
		&i.RecurringType,
		&i.Priority,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.SourceRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
