// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: materialize.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countLegacyExpenses = `-- name: CountLegacyExpenses :one
SELECT COUNT(*)::bigint AS legacy_count FROM expenses
WHERE recurring_type != 'one-time' AND source_rule_id IS NULL
`

func (q *Queries) CountLegacyExpenses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLegacyExpenses)
	var legacy_count int64
	err := row.Scan(&legacy_count)
	return legacy_count, err
}

const countLegacyIncomes = `-- name: CountLegacyIncomes :one
SELECT COUNT(*)::bigint AS legacy_count FROM incomes
WHERE recurring_type != 'one-time' AND source_rule_id IS NULL
`

func (q *Queries) CountLegacyIncomes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLegacyIncomes)
	var legacy_count int64
	err := row.Scan(&legacy_count)
	return legacy_count, err
}

const createExpenseInstance = `-- name: CreateExpenseInstance :execrows
INSERT INTO expenses (user_id, category_id, amount, currency, description, notes, expense_date, recurring_type, priority, status, is_debt, start_date, end_date, source_rule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'one-time', $8, 'posted', $9, NULL, NULL, $10)
ON CONFLICT (user_id, source_rule_id, expense_date) WHERE source_rule_id IS NOT NULL DO NOTHING
`

type CreateExpenseInstanceParams struct {
	UserID       uuid.UUID       `db:"user_id" json:"user_id"`
	CategoryID   pgtype.UUID     `db:"category_id" json:"category_id"`
	Amount       decimal.Decimal `db:"amount" json:"amount"`
	Currency     string          `db:"currency" json:"currency"`
	Description  string          `db:"description" json:"description"`
	Notes        pgtype.Text     `db:"notes" json:"notes"`
	ExpenseDate  pgtype.Date     `db:"expense_date" json:"expense_date"`
	Priority     string          `db:"priority" json:"priority"`
	IsDebt       bool            `db:"is_debt" json:"is_debt"`
	SourceRuleID pgtype.UUID     `db:"source_rule_id" json:"source_rule_id"`
}

func (q *Queries) CreateExpenseInstance(ctx context.Context, arg CreateExpenseInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, createExpenseInstance,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.ExpenseDate,
		arg.Priority,
		arg.IsDebt,
		arg.SourceRuleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createIncomeInstance = `-- name: CreateIncomeInstance :execrows
INSERT INTO incomes (user_id, category_id, amount, currency, description, notes, date, recurring_type, priority, status, start_date, end_date, source_rule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'one-time', $8, 'posted', NULL, NULL, $9)
ON CONFLICT (user_id, source_rule_id, date) WHERE source_rule_id IS NOT NULL DO NOTHING
`

type CreateIncomeInstanceParams struct {
	UserID       uuid.UUID       `db:"user_id" json:"user_id"`
	CategoryID   pgtype.UUID     `db:"category_id" json:"category_id"`
	Amount       decimal.Decimal `db:"amount" json:"amount"`
	Currency     string          `db:"currency" json:"currency"`
	Description  string          `db:"description" json:"description"`
	Notes        pgtype.Text     `db:"notes" json:"notes"`
	Date         pgtype.Date     `db:"date" json:"date"`
	Priority     string          `db:"priority" json:"priority"`
	SourceRuleID pgtype.UUID     `db:"source_rule_id" json:"source_rule_id"`
}

func (q *Queries) CreateIncomeInstance(ctx context.Context, arg CreateIncomeInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, createIncomeInstance,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.Date,
		arg.Priority,
		arg.SourceRuleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const flipLegacyExpenseToOneTime = `-- name: FlipLegacyExpenseToOneTime :exec
UPDATE expenses SET recurring_type = 'one-time', updated_at = now()
WHERE id = $1
`

func (q *Queries) FlipLegacyExpenseToOneTime(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, flipLegacyExpenseToOneTime, id)
	return err
}

const flipLegacyIncomeToOneTime = `-- name: FlipLegacyIncomeToOneTime :exec
UPDATE incomes SET recurring_type = 'one-time', updated_at = now()
WHERE id = $1
`

func (q *Queries) FlipLegacyIncomeToOneTime(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, flipLegacyIncomeToOneTime, id)
	return err
}

const listActiveExpenseRules = `-- name: ListActiveExpenseRules :many

SELECT id, user_id, description, amount, currency, category_id, notes, recurring_type, start_date, end_date, priority, is_active, created_at, updated_at FROM recurring_expense_rules
WHERE is_active = true
  AND start_date <= $1
  AND (end_date IS NULL OR end_date >= $1)
ORDER BY start_date ASC
`

// Worker materialization queries (D3/D4/D5): active-rule selection, idempotent
// instance inserts, and legacy inline-rule backfill support.
func (q *Queries) ListActiveExpenseRules(ctx context.Context, startDate pgtype.Date) ([]RecurringExpenseRule, error) {
	rows, err := q.db.Query(ctx, listActiveExpenseRules, startDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpenseRule{}
	for rows.Next() {
		var i RecurringExpenseRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.Notes,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveIncomeRules = `-- name: ListActiveIncomeRules :many
SELECT id, user_id, amount, currency, description, recurring_type, start_date, end_date, created_at, updated_at FROM recurring_income_rules
WHERE start_date <= $1
  AND (end_date IS NULL OR end_date >= $1)
ORDER BY start_date ASC
`

func (q *Queries) ListActiveIncomeRules(ctx context.Context, startDate pgtype.Date) ([]RecurringIncomeRule, error) {
	rows, err := q.db.Query(ctx, listActiveIncomeRules, startDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringIncomeRule{}
	for rows.Next() {
		var i RecurringIncomeRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyExpenses = `-- name: ListLegacyExpenses :many
SELECT id, user_id, category_id, amount, currency, description, notes, expense_date, recurring_type, priority, status, is_debt, start_date, end_date, source_rule_id, created_at, updated_at FROM expenses
WHERE recurring_type != 'one-time' AND source_rule_id IS NULL
ORDER BY start_date ASC NULLS LAST, expense_date ASC
`

func (q *Queries) ListLegacyExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listLegacyExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.ExpenseDate,
			&i.RecurringType,
			&i.Priority,
			&i.Status,
			&i.IsDebt,
			&i.StartDate,
			&i.EndDate,
			&i.SourceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyIncomes = `-- name: ListLegacyIncomes :many
SELECT id, user_id, category_id, amount, currency, description, notes, date, recurring_type, priority, status, start_date, end_date, source_rule_id, created_at, updated_at FROM incomes
WHERE recurring_type != 'one-time' AND source_rule_id IS NULL
ORDER BY start_date ASC NULLS LAST, date ASC
`

func (q *Queries) ListLegacyIncomes(ctx context.Context) ([]Income, error) {
	rows, err := q.db.Query(ctx, listLegacyIncomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.Date,
			&i.RecurringType,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.SourceRuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
