// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Amount        pgtype.Numeric     `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   string             `db:"description" json:"description"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate   pgtype.Date        `db:"expense_date" json:"expense_date"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	Priority      string             `db:"priority" json:"priority"`
	Status        string             `db:"status" json:"status"`
	IsDebt        bool               `db:"is_debt" json:"is_debt"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID        `db:"source_rule_id" json:"source_rule_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ExpenseCategory struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Name      string             `db:"name" json:"name"`
	Color     pgtype.Text        `db:"color" json:"color"`
	Icon      pgtype.Text        `db:"icon" json:"icon"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ExpenseTag struct {
	ExpenseID uuid.UUID `db:"expense_id" json:"expense_id"`
	TagID     uuid.UUID `db:"tag_id" json:"tag_id"`
}

type Income struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Amount        pgtype.Numeric     `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   string             `db:"description" json:"description"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	Date          pgtype.Date        `db:"date" json:"date"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	Priority      string             `db:"priority" json:"priority"`
	Status        string             `db:"status" json:"status"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	SourceRuleID  pgtype.UUID        `db:"source_rule_id" json:"source_rule_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IncomeCategory struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Name      string             `db:"name" json:"name"`
	Color     pgtype.Text        `db:"color" json:"color"`
	Icon      pgtype.Text        `db:"icon" json:"icon"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IncomeTag struct {
	IncomeID uuid.UUID `db:"income_id" json:"income_id"`
	TagID    uuid.UUID `db:"tag_id" json:"tag_id"`
}

type RecurringExpenseRule struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	Description   string             `db:"description" json:"description"`
	Amount        pgtype.Numeric     `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	Priority      string             `db:"priority" json:"priority"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RecurringIncomeRule struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	Amount        pgtype.Numeric     `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   string             `db:"description" json:"description"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Tag struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Name      string             `db:"name" json:"name"`
	Color     pgtype.Text        `db:"color" json:"color"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
