// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Querier interface {
	AddTagToExpense(ctx context.Context, arg AddTagToExpenseParams) error
	AddTagToIncome(ctx context.Context, arg AddTagToIncomeParams) error
	CheckSkippedExpense(ctx context.Context, arg CheckSkippedExpenseParams) (bool, error)
	CheckSkippedIncome(ctx context.Context, arg CheckSkippedIncomeParams) (bool, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error)
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error)
	CreateIncomeCategory(ctx context.Context, arg CreateIncomeCategoryParams) (IncomeCategory, error)
	CreateRecurringExpenseRule(ctx context.Context, arg CreateRecurringExpenseRuleParams) (RecurringExpenseRule, error)
	CreateRecurringIncomeRule(ctx context.Context, arg CreateRecurringIncomeRuleParams) (RecurringIncomeRule, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error
	DeleteExpenseCategory(ctx context.Context, arg DeleteExpenseCategoryParams) error
	DeleteIncome(ctx context.Context, arg DeleteIncomeParams) error
	DeleteIncomeCategory(ctx context.Context, arg DeleteIncomeCategoryParams) error
	DeleteRecurringExpenseRule(ctx context.Context, arg DeleteRecurringExpenseRuleParams) error
	DeleteRecurringIncomeRule(ctx context.Context, arg DeleteRecurringIncomeRuleParams) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	GetCategoryBreakdown(ctx context.Context, arg GetCategoryBreakdownParams) ([]GetCategoryBreakdownRow, error)
	GetCurrentTotalMoney(ctx context.Context, arg GetCurrentTotalMoneyParams) (decimal.Decimal, error)
	GetExpense(ctx context.Context, arg GetExpenseParams) (GetExpenseRow, error)
	GetExpenseCategory(ctx context.Context, arg GetExpenseCategoryParams) (ExpenseCategory, error)
	GetExpenseStatsByCategory(ctx context.Context, arg GetExpenseStatsByCategoryParams) ([]GetExpenseStatsByCategoryRow, error)
	GetFiftyThirtyTwenty(ctx context.Context, arg GetFiftyThirtyTwentyParams) (GetFiftyThirtyTwentyRow, error)
	GetIncome(ctx context.Context, arg GetIncomeParams) (GetIncomeRow, error)
	GetIncomeCategory(ctx context.Context, arg GetIncomeCategoryParams) (IncomeCategory, error)
	GetIncomeOccurrences(ctx context.Context, arg GetIncomeOccurrencesParams) ([]Income, error)
	GetMonthOverMonthTrends(ctx context.Context, arg GetMonthOverMonthTrendsParams) ([]GetMonthOverMonthTrendsRow, error)
	GetRecurringExpenseRule(ctx context.Context, arg GetRecurringExpenseRuleParams) (GetRecurringExpenseRuleRow, error)
	GetRecurringIncomeRule(ctx context.Context, arg GetRecurringIncomeRuleParams) (RecurringIncomeRule, error)
	GetSavingsRate(ctx context.Context, arg GetSavingsRateParams) (GetSavingsRateRow, error)
	GetSpendingVelocity(ctx context.Context, arg GetSpendingVelocityParams) (GetSpendingVelocityRow, error)
	GetSummary(ctx context.Context, arg GetSummaryParams) (GetSummaryRow, error)
	GetTag(ctx context.Context, arg GetTagParams) (Tag, error)
	GetTagsByExpenseID(ctx context.Context, expenseID uuid.UUID) ([]Tag, error)
	GetTagsByIncomeID(ctx context.Context, incomeID uuid.UUID) ([]Tag, error)
	GetTotalExpensesByDateRange(ctx context.Context, arg GetTotalExpensesByDateRangeParams) (decimal.Decimal, error)
	GetTotalIncomesByDateRange(ctx context.Context, arg GetTotalIncomesByDateRangeParams) (decimal.Decimal, error)
	GetTrends(ctx context.Context, arg GetTrendsParams) ([]GetTrendsRow, error)
	GetUpcomingRecurringExpenses(ctx context.Context, userID uuid.UUID) ([]GetUpcomingRecurringExpensesRow, error)
	ListAllExpenseTagsByUser(ctx context.Context, userID uuid.UUID) ([]ExpenseTag, error)
	ListAllExpensesByUser(ctx context.Context, userID uuid.UUID) ([]Expense, error)
	ListAllIncomeTagsByUser(ctx context.Context, userID uuid.UUID) ([]IncomeTag, error)
	ListAllIncomesByUser(ctx context.Context, userID uuid.UUID) ([]Income, error)
	ListExpenseCategories(ctx context.Context, userID uuid.UUID) ([]ExpenseCategory, error)
	ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error)
	ListIncomeCategories(ctx context.Context, userID uuid.UUID) ([]IncomeCategory, error)
	ListIncomes(ctx context.Context, arg ListIncomesParams) ([]ListIncomesRow, error)
	ListRecurringExpenseRules(ctx context.Context, userID uuid.UUID) ([]ListRecurringExpenseRulesRow, error)
	ListRecurringIncomeRules(ctx context.Context, userID uuid.UUID) ([]RecurringIncomeRule, error)
	ListTags(ctx context.Context, userID uuid.UUID) ([]Tag, error)
	RemoveTagFromExpense(ctx context.Context, arg RemoveTagFromExpenseParams) error
	RemoveTagFromIncome(ctx context.Context, arg RemoveTagFromIncomeParams) error
	SearchExpenses(ctx context.Context, arg SearchExpensesParams) ([]SearchExpensesRow, error)
	SkipExpense(ctx context.Context, arg SkipExpenseParams) error
	SkipIncome(ctx context.Context, arg SkipIncomeParams) error
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error)
	UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error)
	UpdateIncomeCategory(ctx context.Context, arg UpdateIncomeCategoryParams) (IncomeCategory, error)
	UpdateRecurringExpenseRule(ctx context.Context, arg UpdateRecurringExpenseRuleParams) (RecurringExpenseRule, error)
	UpdateRecurringIncomeRule(ctx context.Context, arg UpdateRecurringIncomeRuleParams) (RecurringIncomeRule, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
