// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_income_rules.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringIncomeRule = `-- name: CreateRecurringIncomeRule :one
INSERT INTO recurring_income_rules (user_id, amount, currency, description, recurring_type, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, amount, currency, description, recurring_type, start_date, end_date, created_at, updated_at
`

type CreateRecurringIncomeRuleParams struct {
	UserID        uuid.UUID      `db:"user_id" json:"user_id"`
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	Currency      string         `db:"currency" json:"currency"`
	Description   string         `db:"description" json:"description"`
	RecurringType string         `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date    `db:"end_date" json:"end_date"`
}

func (q *Queries) CreateRecurringIncomeRule(ctx context.Context, arg CreateRecurringIncomeRuleParams) (RecurringIncomeRule, error) {
	row := q.db.QueryRow(ctx, createRecurringIncomeRule,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
	)
	var i RecurringIncomeRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurringIncomeRule = `-- name: DeleteRecurringIncomeRule :exec
DELETE FROM recurring_income_rules
WHERE id = $1 AND user_id = $2
`

type DeleteRecurringIncomeRuleParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteRecurringIncomeRule(ctx context.Context, arg DeleteRecurringIncomeRuleParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringIncomeRule, arg.ID, arg.UserID)
	return err
}

const getRecurringIncomeRule = `-- name: GetRecurringIncomeRule :one
SELECT id, user_id, amount, currency, description, recurring_type, start_date, end_date, created_at, updated_at FROM recurring_income_rules
WHERE id = $1 AND user_id = $2
`

type GetRecurringIncomeRuleParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetRecurringIncomeRule(ctx context.Context, arg GetRecurringIncomeRuleParams) (RecurringIncomeRule, error) {
	row := q.db.QueryRow(ctx, getRecurringIncomeRule, arg.ID, arg.UserID)
	var i RecurringIncomeRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecurringIncomeRules = `-- name: ListRecurringIncomeRules :many
SELECT id, user_id, amount, currency, description, recurring_type, start_date, end_date, created_at, updated_at FROM recurring_income_rules
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRecurringIncomeRules(ctx context.Context, userID uuid.UUID) ([]RecurringIncomeRule, error) {
	rows, err := q.db.Query(ctx, listRecurringIncomeRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringIncomeRule{}
	for rows.Next() {
		var i RecurringIncomeRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringIncomeRule = `-- name: UpdateRecurringIncomeRule :one
UPDATE recurring_income_rules
SET amount = $3, currency = $4, description = $5, recurring_type = $6,
    start_date = $7, end_date = $8, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, amount, currency, description, recurring_type, start_date, end_date, created_at, updated_at
`

type UpdateRecurringIncomeRuleParams struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	UserID        uuid.UUID      `db:"user_id" json:"user_id"`
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	Currency      string         `db:"currency" json:"currency"`
	Description   string         `db:"description" json:"description"`
	RecurringType string         `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date    `db:"end_date" json:"end_date"`
}

func (q *Queries) UpdateRecurringIncomeRule(ctx context.Context, arg UpdateRecurringIncomeRuleParams) (RecurringIncomeRule, error) {
	row := q.db.QueryRow(ctx, updateRecurringIncomeRule,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
	)
	var i RecurringIncomeRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
