// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_expense_rules.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createRecurringExpenseRule = `-- name: CreateRecurringExpenseRule :one
INSERT INTO recurring_expense_rules (user_id, description, amount, currency, category_id, notes, recurring_type, start_date, end_date, priority)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, description, amount, currency, category_id, notes, recurring_type, start_date, end_date, priority, is_active, created_at, updated_at
`

type CreateRecurringExpenseRuleParams struct {
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	Description   string          `db:"description" json:"description"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Currency      string          `db:"currency" json:"currency"`
	CategoryID    pgtype.UUID     `db:"category_id" json:"category_id"`
	Notes         pgtype.Text     `db:"notes" json:"notes"`
	RecurringType string          `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date     `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date     `db:"end_date" json:"end_date"`
	Priority      string          `db:"priority" json:"priority"`
}

func (q *Queries) CreateRecurringExpenseRule(ctx context.Context, arg CreateRecurringExpenseRuleParams) (RecurringExpenseRule, error) {
	row := q.db.QueryRow(ctx, createRecurringExpenseRule,
		arg.UserID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.Notes,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
		arg.Priority,
	)
	var i RecurringExpenseRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.Notes,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurringExpenseRule = `-- name: DeleteRecurringExpenseRule :exec
DELETE FROM recurring_expense_rules
WHERE id = $1 AND user_id = $2
`

type DeleteRecurringExpenseRuleParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteRecurringExpenseRule(ctx context.Context, arg DeleteRecurringExpenseRuleParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringExpenseRule, arg.ID, arg.UserID)
	return err
}

const getRecurringExpenseRule = `-- name: GetRecurringExpenseRule :one
SELECT r.id, r.user_id, r.description, r.amount, r.currency, r.category_id, r.notes, r.recurring_type, r.start_date, r.end_date, r.priority, r.is_active, r.created_at, r.updated_at, ec.name AS category_name, ec.color AS category_color, ec.icon AS category_icon
FROM recurring_expense_rules r
LEFT JOIN expense_categories ec ON r.category_id = ec.id
WHERE r.id = $1 AND r.user_id = $2
`

type GetRecurringExpenseRuleParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type GetRecurringExpenseRuleRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	Description   string             `db:"description" json:"description"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	Priority      string             `db:"priority" json:"priority"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName  pgtype.Text        `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text        `db:"category_color" json:"category_color"`
	CategoryIcon  pgtype.Text        `db:"category_icon" json:"category_icon"`
}

func (q *Queries) GetRecurringExpenseRule(ctx context.Context, arg GetRecurringExpenseRuleParams) (GetRecurringExpenseRuleRow, error) {
	row := q.db.QueryRow(ctx, getRecurringExpenseRule, arg.ID, arg.UserID)
	var i GetRecurringExpenseRuleRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.Notes,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryColor,
		&i.CategoryIcon,
	)
	return i, err
}

const listRecurringExpenseRules = `-- name: ListRecurringExpenseRules :many
SELECT r.id, r.user_id, r.description, r.amount, r.currency, r.category_id, r.notes, r.recurring_type, r.start_date, r.end_date, r.priority, r.is_active, r.created_at, r.updated_at, ec.name AS category_name, ec.color AS category_color, ec.icon AS category_icon
FROM recurring_expense_rules r
LEFT JOIN expense_categories ec ON r.category_id = ec.id
WHERE r.user_id = $1 AND r.is_active = true
ORDER BY r.created_at DESC
`

type ListRecurringExpenseRulesRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	Description   string             `db:"description" json:"description"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	Priority      string             `db:"priority" json:"priority"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName  pgtype.Text        `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text        `db:"category_color" json:"category_color"`
	CategoryIcon  pgtype.Text        `db:"category_icon" json:"category_icon"`
}

func (q *Queries) ListRecurringExpenseRules(ctx context.Context, userID uuid.UUID) ([]ListRecurringExpenseRulesRow, error) {
	rows, err := q.db.Query(ctx, listRecurringExpenseRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringExpenseRulesRow{}
	for rows.Next() {
		var i ListRecurringExpenseRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.Notes,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringExpenseRule = `-- name: UpdateRecurringExpenseRule :one
UPDATE recurring_expense_rules
SET description = $3, amount = $4, currency = $5, category_id = $6, notes = $7,
    recurring_type = $8, start_date = $9, end_date = $10, priority = $11,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, description, amount, currency, category_id, notes, recurring_type, start_date, end_date, priority, is_active, created_at, updated_at
`

type UpdateRecurringExpenseRuleParams struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	Description   string          `db:"description" json:"description"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Currency      string          `db:"currency" json:"currency"`
	CategoryID    pgtype.UUID     `db:"category_id" json:"category_id"`
	Notes         pgtype.Text     `db:"notes" json:"notes"`
	RecurringType string          `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date     `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date     `db:"end_date" json:"end_date"`
	Priority      string          `db:"priority" json:"priority"`
}

func (q *Queries) UpdateRecurringExpenseRule(ctx context.Context, arg UpdateRecurringExpenseRuleParams) (RecurringExpenseRule, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpenseRule,
		arg.ID,
		arg.UserID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.Notes,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
		arg.Priority,
	)
	var i RecurringExpenseRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.Notes,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
