// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const listActiveExpenseRulesAllUsers = `-- name: ListActiveExpenseRulesAllUsers :many

SELECT id, user_id, description, amount, currency, recurring_type,
    start_date, end_date
FROM recurring_expense_rules
WHERE is_active = true
ORDER BY start_date ASC
`

type ListActiveExpenseRulesAllUsersRow struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	Description   string          `db:"description" json:"description"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Currency      string          `db:"currency" json:"currency"`
	RecurringType string          `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date     `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date     `db:"end_date" json:"end_date"`
}

// Service endpoints (cross-user reads for service identities).
// These back scope-gated /internal/* routes called with service JWTs;
// they intentionally carry no user filter. Row-level shape mirrors the
// user-scoped recurring rule listings minus ownership checks.
func (q *Queries) ListActiveExpenseRulesAllUsers(ctx context.Context) ([]ListActiveExpenseRulesAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listActiveExpenseRulesAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveExpenseRulesAllUsersRow{}
	for rows.Next() {
		var i ListActiveExpenseRulesAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveIncomeRulesAllUsers = `-- name: ListActiveIncomeRulesAllUsers :many
SELECT id, user_id, description, amount, currency, recurring_type,
    start_date, end_date
FROM recurring_income_rules
WHERE is_active = true
ORDER BY start_date ASC
`

type ListActiveIncomeRulesAllUsersRow struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	Description   string          `db:"description" json:"description"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Currency      string          `db:"currency" json:"currency"`
	RecurringType string          `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date     `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date     `db:"end_date" json:"end_date"`
}

func (q *Queries) ListActiveIncomeRulesAllUsers(ctx context.Context) ([]ListActiveIncomeRulesAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listActiveIncomeRulesAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveIncomeRulesAllUsersRow{}
	for rows.Next() {
		var i ListActiveIncomeRulesAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
