// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT
    ec.id AS category_id,
    ec.name AS category_name,
    ec.color AS category_color,
    COUNT(e.id) AS expense_count,
    COALESCE(SUM(e.amount), 0)::numeric AS total_amount
FROM expense_categories ec
LEFT JOIN expenses e ON ec.id = e.category_id
    AND e.user_id = $1
    AND e.status != 'skipped'
    AND ($2::date IS NULL OR e.expense_date >= $2)
    AND ($3::date IS NULL OR e.expense_date <= $3)
WHERE ec.user_id = $1 AND ec.is_active = true
GROUP BY ec.id, ec.name, ec.color
ORDER BY total_amount DESC
`

type GetCategoryBreakdownParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetCategoryBreakdownRow struct {
	CategoryID    uuid.UUID       `db:"category_id" json:"category_id"`
	CategoryName  string          `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text     `db:"category_color" json:"category_color"`
	ExpenseCount  int64           `db:"expense_count" json:"expense_count"`
	TotalAmount   decimal.Decimal `db:"total_amount" json:"total_amount"`
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context, arg GetCategoryBreakdownParams) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdown, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryBreakdownRow{}
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.ExpenseCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentTotalMoney = `-- name: GetCurrentTotalMoney :one
SELECT
    (COALESCE(SUM(CASE WHEN i.status != 'skipped' THEN i.amount ELSE 0 END), 0)
     - COALESCE(SUM(CASE WHEN e.status != 'skipped' THEN e.amount ELSE 0 END), 0))::numeric AS total_money
FROM expenses e
FULL OUTER JOIN incomes i ON e.user_id = i.user_id
WHERE (e.user_id = $1 OR i.user_id = $1)
  AND (e.expense_date >= $2 OR e.expense_date IS NULL OR $2 IS NULL)
  AND (e.expense_date <= $3 OR e.expense_date IS NULL OR $3 IS NULL)
  AND (i.date >= $2 OR i.date IS NULL OR $2 IS NULL)
  AND (i.date <= $3 OR i.date IS NULL OR $3 IS NULL)
`

type GetCurrentTotalMoneyParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

func (q *Queries) GetCurrentTotalMoney(ctx context.Context, arg GetCurrentTotalMoneyParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getCurrentTotalMoney, arg.UserID, arg.StartDate, arg.EndDate)
	var total_money decimal.Decimal
	err := row.Scan(&total_money)
	return total_money, err
}

const getFiftyThirtyTwenty = `-- name: GetFiftyThirtyTwenty :one
WITH totals AS (
    SELECT
        COALESCE(SUM(CASE WHEN e.status != 'skipped' THEN e.amount ELSE 0 END), 0)::numeric AS total_expenses,
        COALESCE(SUM(CASE WHEN i.status != 'skipped' THEN i.amount ELSE 0 END), 0)::numeric AS total_incomes
    FROM expenses e
    FULL OUTER JOIN incomes i ON e.user_id = i.user_id
    WHERE (e.user_id = $1 OR i.user_id = $1)
      AND (e.expense_date >= $2 OR e.expense_date IS NULL OR $2 IS NULL)
      AND (e.expense_date <= $3 OR e.expense_date IS NULL OR $3 IS NULL)
      AND (i.date >= $2 OR i.date IS NULL OR $2 IS NULL)
      AND (i.date <= $3 OR i.date IS NULL OR $3 IS NULL)
),
category_totals AS (
    SELECT
        COALESCE(SUM(CASE WHEN e.priority = 'need' AND e.status != 'skipped' THEN e.amount ELSE 0 END), 0)::numeric AS needs,
        COALESCE(SUM(CASE WHEN e.priority = 'want' AND e.status != 'skipped' THEN e.amount ELSE 0 END), 0)::numeric AS wants,
        COALESCE(SUM(CASE WHEN e.priority = 'savings' AND e.status != 'skipped' THEN e.amount ELSE 0 END), 0)::numeric AS savings
    FROM expenses e
    WHERE e.user_id = $1
      AND ($2::date IS NULL OR e.expense_date >= $2)
      AND ($3::date IS NULL OR e.expense_date <= $3)
)
SELECT
    t.total_incomes,
    t.total_expenses,
    c.needs,
    c.wants,
    c.savings,
    CASE WHEN t.total_expenses = 0 THEN 0 ELSE (c.needs / t.total_expenses * 100)::numeric END AS needs_pct,
    CASE WHEN t.total_expenses = 0 THEN 0 ELSE (c.wants / t.total_expenses * 100)::numeric END AS wants_pct,
    CASE WHEN t.total_expenses = 0 THEN 0 ELSE (c.savings / t.total_expenses * 100)::numeric END AS savings_pct
FROM totals t, category_totals c
`

type GetFiftyThirtyTwentyParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetFiftyThirtyTwentyRow struct {
	TotalIncomes  decimal.Decimal `db:"total_incomes" json:"total_incomes"`
	TotalExpenses decimal.Decimal `db:"total_expenses" json:"total_expenses"`
	Needs         decimal.Decimal `db:"needs" json:"needs"`
	Wants         decimal.Decimal `db:"wants" json:"wants"`
	Savings       decimal.Decimal `db:"savings" json:"savings"`
	NeedsPct      decimal.Decimal `db:"needs_pct" json:"needs_pct"`
	WantsPct      decimal.Decimal `db:"wants_pct" json:"wants_pct"`
	SavingsPct    decimal.Decimal `db:"savings_pct" json:"savings_pct"`
}

func (q *Queries) GetFiftyThirtyTwenty(ctx context.Context, arg GetFiftyThirtyTwentyParams) (GetFiftyThirtyTwentyRow, error) {
	row := q.db.QueryRow(ctx, getFiftyThirtyTwenty, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetFiftyThirtyTwentyRow
	err := row.Scan(
		&i.TotalIncomes,
		&i.TotalExpenses,
		&i.Needs,
		&i.Wants,
		&i.Savings,
		&i.NeedsPct,
		&i.WantsPct,
		&i.SavingsPct,
	)
	return i, err
}

const getMonthOverMonthTrends = `-- name: GetMonthOverMonthTrends :many
SELECT
    month,
    SUM(total)::numeric AS total_amount
FROM (
    SELECT
        TO_CHAR(e.expense_date, 'YYYY-MM') AS month,
        COALESCE(SUM(e.amount), 0)::numeric AS total
    FROM expenses e
    WHERE e.user_id = $1
      AND e.expense_date >= $2
      AND e.expense_date <= $3
      AND e.status != 'skipped'
    GROUP BY TO_CHAR(e.expense_date, 'YYYY-MM')
    UNION ALL
    SELECT
        TO_CHAR(i.date, 'YYYY-MM') AS month,
        COALESCE(SUM(i.amount), 0)::numeric AS total
    FROM incomes i
    WHERE i.user_id = $1
      AND i.date >= $2
      AND i.date <= $3
      AND i.status != 'skipped'
    GROUP BY TO_CHAR(i.date, 'YYYY-MM')
) AS monthly_data
GROUP BY month
ORDER BY month DESC
`

type GetMonthOverMonthTrendsParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetMonthOverMonthTrendsRow struct {
	Month       string          `db:"month" json:"month"`
	TotalAmount decimal.Decimal `db:"total_amount" json:"total_amount"`
}

func (q *Queries) GetMonthOverMonthTrends(ctx context.Context, arg GetMonthOverMonthTrendsParams) ([]GetMonthOverMonthTrendsRow, error) {
	rows, err := q.db.Query(ctx, getMonthOverMonthTrends, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthOverMonthTrendsRow{}
	for rows.Next() {
		var i GetMonthOverMonthTrendsRow
		if err := rows.Scan(&i.Month, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavingsRate = `-- name: GetSavingsRate :one
WITH totals AS (
    SELECT
        COALESCE(SUM(CASE WHEN e.status != 'skipped' THEN e.amount ELSE 0 END), 0)::numeric AS total_expenses,
        COALESCE(SUM(CASE WHEN i.status != 'skipped' THEN i.amount ELSE 0 END), 0)::numeric AS total_incomes
    FROM expenses e
    FULL OUTER JOIN incomes i ON e.user_id = i.user_id
    WHERE (e.user_id = $1 OR i.user_id = $1)
      AND (e.expense_date >= $2 OR e.expense_date IS NULL OR $2 IS NULL)
      AND (e.expense_date <= $3 OR e.expense_date IS NULL OR $3 IS NULL)
      AND (i.date >= $2 OR i.date IS NULL OR $2 IS NULL)
      AND (i.date <= $3 OR i.date IS NULL OR $3 IS NULL)
)
SELECT
    total_incomes,
    total_expenses,
    CASE
        WHEN total_incomes = 0 THEN 0
        ELSE ((total_incomes - total_expenses) / total_incomes * 100)::numeric
    END AS savings_rate
FROM totals
`

type GetSavingsRateParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetSavingsRateRow struct {
	TotalIncomes  decimal.Decimal `db:"total_incomes" json:"total_incomes"`
	TotalExpenses decimal.Decimal `db:"total_expenses" json:"total_expenses"`
	SavingsRate   decimal.Decimal `db:"savings_rate" json:"savings_rate"`
}

func (q *Queries) GetSavingsRate(ctx context.Context, arg GetSavingsRateParams) (GetSavingsRateRow, error) {
	row := q.db.QueryRow(ctx, getSavingsRate, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetSavingsRateRow
	err := row.Scan(&i.TotalIncomes, &i.TotalExpenses, &i.SavingsRate)
	return i, err
}

const getSpendingVelocity = `-- name: GetSpendingVelocity :one
SELECT
    COALESCE(AVG(monthly_total), 0)::numeric AS avg_monthly_spending,
    COUNT(*)::int AS months_with_data
FROM (
    SELECT
        DATE_TRUNC('month', e.expense_date) AS month,
        SUM(e.amount)::numeric AS monthly_total
    FROM expenses e
    WHERE e.user_id = $1
      AND e.expense_date >= $2
      AND e.expense_date <= $3
      AND e.status != 'skipped'
    GROUP BY DATE_TRUNC('month', e.expense_date)
    ORDER BY month
) AS monthly
`

type GetSpendingVelocityParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetSpendingVelocityRow struct {
	AvgMonthlySpending decimal.Decimal `db:"avg_monthly_spending" json:"avg_monthly_spending"`
	MonthsWithData     int32           `db:"months_with_data" json:"months_with_data"`
}

func (q *Queries) GetSpendingVelocity(ctx context.Context, arg GetSpendingVelocityParams) (GetSpendingVelocityRow, error) {
	row := q.db.QueryRow(ctx, getSpendingVelocity, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetSpendingVelocityRow
	err := row.Scan(&i.AvgMonthlySpending, &i.MonthsWithData)
	return i, err
}

const getSummary = `-- name: GetSummary :one
SELECT
    COALESCE(SUM(CASE WHEN e.status != 'skipped' THEN e.amount ELSE 0 END), 0)::numeric AS total_expenses,
    COALESCE(SUM(CASE WHEN i.status != 'skipped' THEN i.amount ELSE 0 END), 0)::numeric AS total_incomes,
    COUNT(DISTINCT e.id) FILTER (WHERE e.status != 'skipped') AS expense_count,
    COUNT(DISTINCT i.id) FILTER (WHERE i.status != 'skipped') AS income_count
FROM expenses e
FULL OUTER JOIN incomes i ON e.user_id = i.user_id
WHERE (e.user_id = $1 OR i.user_id = $1)
  AND (e.expense_date >= $2 OR e.expense_date IS NULL OR $2 IS NULL)
  AND (e.expense_date <= $3 OR e.expense_date IS NULL OR $3 IS NULL)
  AND (i.date >= $2 OR i.date IS NULL OR $2 IS NULL)
  AND (i.date <= $3 OR i.date IS NULL OR $3 IS NULL)
`

type GetSummaryParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetSummaryRow struct {
	TotalExpenses decimal.Decimal `db:"total_expenses" json:"total_expenses"`
	TotalIncomes  decimal.Decimal `db:"total_incomes" json:"total_incomes"`
	ExpenseCount  int64           `db:"expense_count" json:"expense_count"`
	IncomeCount   int64           `db:"income_count" json:"income_count"`
}

func (q *Queries) GetSummary(ctx context.Context, arg GetSummaryParams) (GetSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSummary, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetSummaryRow
	err := row.Scan(
		&i.TotalExpenses,
		&i.TotalIncomes,
		&i.ExpenseCount,
		&i.IncomeCount,
	)
	return i, err
}

const getTrends = `-- name: GetTrends :many
SELECT
    TO_CHAR(COALESCE(e.expense_date, i.date), 'YYYY-MM') AS month,
    COALESCE(SUM(CASE WHEN e.status != 'skipped' THEN e.amount ELSE 0 END), 0)::numeric AS total_expenses,
    COALESCE(SUM(CASE WHEN i.status != 'skipped' THEN i.amount ELSE 0 END), 0)::numeric AS total_incomes
FROM expenses e
FULL OUTER JOIN incomes i ON e.user_id = i.user_id AND TO_CHAR(COALESCE(e.expense_date, i.date), 'YYYY-MM') = TO_CHAR(i.date, 'YYYY-MM')
WHERE (e.user_id = $1 OR i.user_id = $1)
  AND (e.expense_date >= $2 OR e.expense_date IS NULL OR $2 IS NULL)
  AND (e.expense_date <= $3 OR e.expense_date IS NULL OR $3 IS NULL)
  AND (i.date >= $2 OR i.date IS NULL OR $2 IS NULL)
  AND (i.date <= $3 OR i.date IS NULL OR $3 IS NULL)
GROUP BY TO_CHAR(COALESCE(e.expense_date, i.date), 'YYYY-MM')
ORDER BY month DESC
`

type GetTrendsParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

type GetTrendsRow struct {
	Month         string          `db:"month" json:"month"`
	TotalExpenses decimal.Decimal `db:"total_expenses" json:"total_expenses"`
	TotalIncomes  decimal.Decimal `db:"total_incomes" json:"total_incomes"`
}

func (q *Queries) GetTrends(ctx context.Context, arg GetTrendsParams) ([]GetTrendsRow, error) {
	rows, err := q.db.Query(ctx, getTrends, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrendsRow{}
	for rows.Next() {
		var i GetTrendsRow
		if err := rows.Scan(&i.Month, &i.TotalExpenses, &i.TotalIncomes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingRecurringExpenses = `-- name: GetUpcomingRecurringExpenses :many
SELECT r.id, r.user_id, r.description, r.amount, r.currency, r.category_id, r.notes, r.recurring_type, r.start_date, r.end_date, r.priority, r.is_active, r.created_at, r.updated_at, ec.name AS category_name, ec.color AS category_color
FROM recurring_expense_rules r
LEFT JOIN expense_categories ec ON r.category_id = ec.id
WHERE r.user_id = $1
  AND r.is_active = true
  AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE)
ORDER BY r.created_at ASC
`

type GetUpcomingRecurringExpensesRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	Description   string             `db:"description" json:"description"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	RecurringType string             `db:"recurring_type" json:"recurring_type"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	Priority      string             `db:"priority" json:"priority"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName  pgtype.Text        `db:"category_name" json:"category_name"`
	CategoryColor pgtype.Text        `db:"category_color" json:"category_color"`
}

func (q *Queries) GetUpcomingRecurringExpenses(ctx context.Context, userID uuid.UUID) ([]GetUpcomingRecurringExpensesRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingRecurringExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingRecurringExpensesRow{}
	for rows.Next() {
		var i GetUpcomingRecurringExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.Notes,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
